apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-web-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-web-metrics
  template:
    metadata:
      labels:
        app: test-web-metrics
    spec:
      containers:
      - name: web
        image: YOUR_DOCKER_IMAGE   # Replace with your actual image
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 5
