name: Update Deployment Manifest

on:
  workflow_run:
    workflows: ["Build and Push to GHCR"]
    types:
      - completed

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update image tag in deployment.yaml
        run: |
          sed -i 's|image: .*|image: ghcr.io/${{ github.repository_owner }}/hello-app:latest|' k8s/deployment.yaml

      - name: Commit and Push Deployment Update
        run: |
          git config user.name "ecniii"
          git config user.email "nabor.ecn@gmail.com"
          git add k8s/deployment.yaml
          git commit -m "Update deployment image to latest" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/ecniii/web-app-ci-cd-test1.git HEAD:main
