name: Build, Push, and Update Deployment

on:
  push:
    branches: [main]

permissions:
  contents: write  # Required to push changes back to the repo

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ghcr.io/${{ github.repository_owner }}/hello-app:${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Update image tag in deployment.yaml
        run: |
          sed -i "s|image: .*|image: $IMAGE_TAG|" k8s/deployment.yaml

      - name: Commit and push updated deployment.yaml
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "ecniii"
          git config user.email "nabor.ecn@gmail.com"

          # Only commit if the file changed
          if ! git diff --quiet; then
            git add k8s/deployment.yaml
            git commit -m "Update deployment image to $IMAGE_TAG"
            git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "No changes to commit."
          fi
